# Generated by Django 4.1.7 on 2023-03-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Void',
        ),
    ]
